
version: 2.1



jobs:

  build:
   
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: npm i 
      - run:  npm run lint
  
  test:
   
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      - run: npm i 
      - run:  npm run lint
  
  analyze :
   
    docker:
      - image: cimg/base:stable
   
    steps:
      - checkout
      
      - run:  npm audit

  
workflows:
  pipepline:
    jobs:
      - build
      - test:
        reqquires:
          - build
      -analyze:
        requires:
          - test
      




